---

language: python
python: 3.7
sudo: required

services:
  - docker

# Install requirements
install:
  - pip3 install tox-travis

# Test all the scenarios against the Ansible versions defined in the tox.ini file
script:
  - tox

# TODO: this should run once
before_deploy:
  - pip install ansible==2.9.13
  - ansible-galaxy install --force --roles-path . -r ./molecule/default/requirements.yml
  - wget -O packer.zip https://releases.hashicorp.com/packer/1.3.1/packer_1.3.1_linux_amd64.zip
  - unzip -o packer.zip
  - sudo apt-get update
  - sudo apt-get install qemu-utils -y
  - pip install --upgrade pip
  - pip install python-swiftclient==3.6.0 python-openstackclient==3.17.0

deploy:
  - provider: script
    travis_wait: 30
    script: bash deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
